name: 'minecraft-whitelist-validator'
description: 'validate Minecraft whitelist.json'
author: 'sksat <sksat@sksat.net>'

inputs:
  json:
    description: whitelist.json
    required: true
    default: 'whitelist.json'
  rdjson:
    description: RDFormat JSON(output)
    required: false

runs:
  using: 'docker'
  image: 'docker://ghcr.io/sksat/minecraft-whitelist-validator:v0.2.0'
  env:
    JSON_FILE: ${{ inputs.json }}
    RDJSON_FILE: ${{ inputs.rdjson }}
