name: 'minecraft-whitelist-validator'
description: 'validate Minecraft whitelist.json'
author: 'sksat <sksat@sksat.net>'

inputs:
  json:
    description: whitelist.json
    required: true
    default: 'whitelist.json'
  rdjson:
    description: RDFormat JSON(output)
    required: false

runs:
  using: 'composite'
  steps:
    - name: install minecraft-whitelist-validator
      shell: bash
      run: |
        cargo install minecraft-whitelist-validator --version 0.3.2 --locked
        minecraft-whitelist-validator --version

    - name: validate whitelist.json
      shell: bash
      run: minecraft-whitelist-validator
      env:
        JSON_FILE: ${{ inputs.json }}
        RDJSON_FILE: ${{ inputs.rdjson }}
