name: test Action

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'renovate.json'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: checkout mc.yohane.su
        uses: actions/checkout@v2
        with:
          repository: sksat/mc.yohane.su
          ref: main
          path: mc.yohane.su

      - name: generate image tag
        id: tag
        run: |
          echo "::set-output name=img_tag::sha-$(git rev-parse --short HEAD)"

      - uses: sksat/minecraft-whitelist-validator@HEAD
        with:
          img_tag: ${{ steps.tag.outputs.img_tag }}
          json: mc.yohane.su/data/whitelist.json
          rdjson: errors.json

      - name: check errors
        run: jq < errors.json
