name: test Action

on:
  workflow_dispatch:
  push:
    branches:
      - composite-action
    paths:
      - 'action.yml'
      - '.github/workflows/test-action.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: checkout mc.yohane.su
        uses: actions/checkout@v2
        with:
          repository: sksat/mc.yohane.su
          ref: main
          path: mc.yohane.su

      - uses: sksat/minecraft-whitelist-validator@composite-action
        with:
          json: mc.yohane.su/data/whitelist.json
          rdjson: errors.json

      - name: check errors
        run: jq < errors.json
